In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\code\py\ML\14_naive_bayes\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df['spam'] = df["Category"].apply(lambda x: 1 if x =='spam' else 0)

In [8]:
df.shape

(5572, 3)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7696 sparse matrix of type '<class 'numpy.int64'>'
	with 59359 stored elements in Compressed Sparse Row format>

In [13]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
X_train_cv.shape

(4457, 7696)

In [15]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zouk', 'zyada', '〨ud'], dtype=object)

In [16]:
v.get_feature_names_out()[1771]

'cheers'

In [ ]:
v.vocabulary_

In [18]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
np.where(X_train_np[0]!=0)

(array([ 775,  883,  901,  941, 1235, 1606, 2509, 2704, 2795, 2884, 3108,
        3210, 3372, 3555, 4254, 4422, 4805, 4909, 4977, 5675, 6026, 6231,
        6526, 6845, 7147, 7543], dtype=int64),)

In [25]:
X_train[:4][560]

'Aiyo... U always c our ex one... I dunno abt mei, she haven reply... First time u reply so fast... Y so lucky not workin huh, got bao by ur sugardad ah...gee..'

In [24]:
y_train[:4]

560     0
813     1
3459    0
618     0
Name: spam, dtype: int64

In [36]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [37]:

X_test_cv = v.transform(X_test)


In [39]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       979
           1       0.96      0.94      0.95       136

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [40]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [41]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [42]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       979
           1       0.96      0.94      0.95       136

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

