In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [18]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

In [19]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9796296296296296

In [20]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9481481481481482

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for  train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [29]:
def get_score(model, X_train, X_test,y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [30]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [35]:
scores_l = []
scores_svm = []
scores_rf = []

for  train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train , y_test = digits.data[train_index],digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [36]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [37]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [38]:
scores_rf

[0.9332220367278798, 0.9465776293823038, 0.9232053422370617]

In [39]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])